### PR TITLE
Added HAVE_DRI3 define and fixed configure patch for libGL

### PR DESCRIPTION
**Pull request by johalun**

### CODE REVIEW

**Comment by valpackett** [comment]
Is DRI3 supposed to work now? I'm getting this error when building libEGL:

```
In file included from drivers/dri2/platform_x11_dri3.c:36:
../../src/egl/drivers/dri2/platform_x11_dri3.h:32:32: error: field has incomplete type 'struct loader_dri3_drawable'
   struct loader_dri3_drawable loader_drawable;
                               ^
../../src/egl/drivers/dri2/platform_x11_dri3.h:32:11: note: forward declaration of 'struct loader_dri3_drawable'
   struct loader_dri3_drawable loader_drawable;
          ^
drivers/dri2/platform_x11_dri3.c:223:45: error: no member named 'loader_dri3_ext' in 'struct dri2_egl_display'
                                 &dri2_dpy->loader_dri3_ext,
                                  ~~~~~~~~  ^
drivers/dri2/platform_x11_dri3.c:274:31: warning: expression which evaluates to zero treated as a null pointer constant of type 'void *'
      [-Wnon-literal-null-conversion]
                              XCB_WINDOW_NONE, attrib_list);
                              ^~~~~~~~~~~~~~~
1 warning and 2 errors generated.
gmake[2]: *** [Makefile:1049: drivers/dri2/platform_x11_dri3.lo] Error 1
gmake[2]: Leaving directory '/usr/ports/graphics/libEGL/work/mesa-12.0.4/src/egl'
```

**Comment by johalun** [comment]
It did work a couple of months ago when I was working on it. Maybe some change I did to mesa for libEGL has been overwritten... I will check.

**Comment by johalun** [comment]
Look like this patch was overwritten somehow. Patched again now so please try again with the xserver-mesa-next branch! @myfreeweb

**Comment by valpackett** [comment]
Thanks! BTW, I found out that DRI3 in libEGL is not necessary for XWayland to work, DRI3 in libGL and Xorg is enough.

**Comment by johalun** [comment]
Ok. But both GL and EGL ports use the same patches that are in the libGL port so only need to update in one place.

**Pull request merged**
